// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: logis.proto

package logis

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto    string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda      string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario int32  `protobuf:"varint,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{0}
}

func (x *Pedido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pedido) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Pedido) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Pedido) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Pedido) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Pedido) GetPrioritario() int32 {
	if x != nil {
		return x.Prioritario
	}
	return 0
}

type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumSeguimiento int32  `protobuf:"varint,2,opt,name=num_seguimiento,json=numSeguimiento,proto3" json:"num_seguimiento,omitempty"`
	Tipo           string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor          int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	NumIntentos    int32  `protobuf:"varint,5,opt,name=num_intentos,json=numIntentos,proto3" json:"num_intentos,omitempty"`
	Estado         string `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{1}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetNumSeguimiento() int32 {
	if x != nil {
		return x.NumSeguimiento
	}
	return 0
}

func (x *Package) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Package) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Package) GetNumIntentos() int32 {
	if x != nil {
		return x.NumIntentos
	}
	return 0
}

func (x *Package) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Geo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origen  string `protobuf:"bytes,1,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino string `protobuf:"bytes,2,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Geo) Reset() {
	*x = Geo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo) ProtoMessage() {}

func (x *Geo) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo.ProtoReflect.Descriptor instead.
func (*Geo) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{2}
}

func (x *Geo) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Geo) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type RegCamion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPkg        string `protobuf:"bytes,1,opt,name=id_pkg,json=idPkg,proto3" json:"id_pkg,omitempty"`
	Tipo         string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor        int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen       string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino      string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	NumIntentos  int32  `protobuf:"varint,6,opt,name=num_intentos,json=numIntentos,proto3" json:"num_intentos,omitempty"`
	FechaEntrega string `protobuf:"bytes,7,opt,name=fecha_entrega,json=fechaEntrega,proto3" json:"fecha_entrega,omitempty"`
}

func (x *RegCamion) Reset() {
	*x = RegCamion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegCamion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegCamion) ProtoMessage() {}

func (x *RegCamion) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegCamion.ProtoReflect.Descriptor instead.
func (*RegCamion) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{3}
}

func (x *RegCamion) GetIdPkg() string {
	if x != nil {
		return x.IdPkg
	}
	return ""
}

func (x *RegCamion) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *RegCamion) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *RegCamion) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *RegCamion) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *RegCamion) GetNumIntentos() int32 {
	if x != nil {
		return x.NumIntentos
	}
	return 0
}

func (x *RegCamion) GetFechaEntrega() string {
	if x != nil {
		return x.FechaEntrega
	}
	return ""
}

type CodSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codigo int32 `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *CodSeguimiento) Reset() {
	*x = CodSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodSeguimiento) ProtoMessage() {}

func (x *CodSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodSeguimiento.ProtoReflect.Descriptor instead.
func (*CodSeguimiento) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{4}
}

func (x *CodSeguimiento) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

type EstadoPedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *EstadoPedido) Reset() {
	*x = EstadoPedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoPedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoPedido) ProtoMessage() {}

func (x *EstadoPedido) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoPedido.ProtoReflect.Descriptor instead.
func (*EstadoPedido) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{5}
}

func (x *EstadoPedido) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo     string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor    int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen   string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino  string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos string `protobuf:"bytes,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{6}
}

func (x *Paquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Paquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Paquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Paquete) GetIntentos() string {
	if x != nil {
		return x.Intentos
	}
	return ""
}

type TipoCam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *TipoCam) Reset() {
	*x = TipoCam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipoCam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipoCam) ProtoMessage() {}

func (x *TipoCam) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipoCam.ProtoReflect.Descriptor instead.
func (*TipoCam) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{7}
}

func (x *TipoCam) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type PaqRecibido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo     string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor    int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos int32  `protobuf:"varint,4,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado   string `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *PaqRecibido) Reset() {
	*x = PaqRecibido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logis_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqRecibido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqRecibido) ProtoMessage() {}

func (x *PaqRecibido) ProtoReflect() protoreflect.Message {
	mi := &file_logis_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqRecibido.ProtoReflect.Descriptor instead.
func (*PaqRecibido) Descriptor() ([]byte, []int) {
	return file_logis_proto_rawDescGZIP(), []int{8}
}

func (x *PaqRecibido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaqRecibido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PaqRecibido) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PaqRecibido) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *PaqRecibido) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_logis_proto protoreflect.FileDescriptor

var file_logis_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72,
	0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x61, 0x72, 0x69, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x53,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x37, 0x0a, 0x03, 0x47, 0x65, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x09, 0x72, 0x65, 0x67,
	0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x64, 0x5f, 0x70, 0x6b, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x50, 0x6b, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6e, 0x75, 0x6d, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x65, 0x63, 0x68, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67,
	0x61, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x6f, 0x64, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x26, 0x0a, 0x0c, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x07, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x74, 0x69, 0x70, 0x6f, 0x43,
	0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x22, 0x7b, 0x0a, 0x0b, 0x70, 0x61, 0x71, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x69, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x32, 0x8b, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x2e, 0x50, 0x65,
	0x64, 0x69, 0x64, 0x6f, 0x1a, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x64,
	0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x12, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x53,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x13, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x22,
	0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x6f, 0x73, 0x65, 0x6d, 0x71, 0x7a, 0x2f, 0x53, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x4c, 0x61, 0x62, 0x31, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x73, 0x3b, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_logis_proto_rawDescOnce sync.Once
	file_logis_proto_rawDescData = file_logis_proto_rawDesc
)

func file_logis_proto_rawDescGZIP() []byte {
	file_logis_proto_rawDescOnce.Do(func() {
		file_logis_proto_rawDescData = protoimpl.X.CompressGZIP(file_logis_proto_rawDescData)
	})
	return file_logis_proto_rawDescData
}

var file_logis_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_logis_proto_goTypes = []interface{}{
	(*Pedido)(nil),         // 0: logis.Pedido
	(*Package)(nil),        // 1: logis.Package
	(*Geo)(nil),            // 2: logis.Geo
	(*RegCamion)(nil),      // 3: logis.regCamion
	(*CodSeguimiento)(nil), // 4: logis.CodSeguimiento
	(*EstadoPedido)(nil),   // 5: logis.EstadoPedido
	(*Paquete)(nil),        // 6: logis.paquete
	(*TipoCam)(nil),        // 7: logis.tipoCam
	(*PaqRecibido)(nil),    // 8: logis.paqRecibido
}
var file_logis_proto_depIdxs = []int32{
	0, // 0: logis.LogisService.PedidoCliente:input_type -> logis.Pedido
	4, // 1: logis.LogisService.SeguimientoCliente:input_type -> logis.CodSeguimiento
	4, // 2: logis.LogisService.PedidoCliente:output_type -> logis.CodSeguimiento
	5, // 3: logis.LogisService.SeguimientoCliente:output_type -> logis.EstadoPedido
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logis_proto_init() }
func file_logis_proto_init() {
	if File_logis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegCamion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoPedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipoCam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logis_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqRecibido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logis_proto_goTypes,
		DependencyIndexes: file_logis_proto_depIdxs,
		MessageInfos:      file_logis_proto_msgTypes,
	}.Build()
	File_logis_proto = out.File
	file_logis_proto_rawDesc = nil
	file_logis_proto_goTypes = nil
	file_logis_proto_depIdxs = nil
}
